# Generated by Django 5.2.8 on 2025-12-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='narration',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
