# Generated by Django 5.2.8 on 2025-12-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='pin_set',
            field=models.BooleanField(default=False),
        ),
    ]
