# Generated by Django 5.2.8 on 2025-12-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='two_factor_authentication',
            field=models.BooleanField(default=False),
        ),
    ]
